kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: aurelius
  name: deployment-manager-binding
subjects:
  - kind: User
    name: robel
    apiGroup: ""
roleRef:
   kind: Role
   name: deployment-manager
   apiGroup: ""
